### ISSUE TITLE
Cannot find package @acdh/network-visualization.umd.js@latest

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/network-visualization#1]
trying to load 
`<script src="https://unpkg.com/@acdh/network-visualization.umd.js"></script> ` throws

> https://unpkg.com/@acdh/network-visualization.umd.js net::ERR_ABORTED 404

**Comment by stefanprobst** [comment]
this is because the package is not yet published to npm

**Comment by stefanprobst** [comment]
Fixed in v0.1.0
